// Guidlines:
// *. currently no better API than youtube...
// *. no need for song store, it is part of the station

// Pages, Cmps:
// HomePage render 2 stations => link StationDetails
// Add station
// AppPlayer (initially rendered at StationDetails, later in footer)
//   Smart component - connected to store:
//   -. stationModule.currentlyPlayingUrl
//   -. stationModule.dispatch(nextSong)
// Filtering
// StationList, StationPreview
// StationDetails - Make it amazing
// D & D Later....

const stations = [
	{
		_id: '5cksxjas89xjsa8xjsa8jxs01',
		name: 'Chill Vibes',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724082806/jevy3fwzckfd94pnyifz.webp',
		tags: ['Chill', 'Relaxing'],
		createdBy: {
			id: 'u102',
			fullname: 'Sam Smith',
			imgUrl: 'https://i.imgur.com/6OLS5bF.jpeg',
		},
		likedByUsers: ['{user-id1}', '{user-id2}'],
		songs: [
			{
				id: 'chill1001',
				title: 'Kiara',
				artist: 'Bonobo',
				album: 'Black Sands',
				url: 'https://youtu.be/L-kyRh7N-kE',
				imgUrl: ['https://i.ytimg.com/vi/S3r5TRU-M-o/mqdefault.jpg'],
				addedAt: 162521795262,
				duration: '3:50',
			},
			{
				id: 'chill1002',
				title: 'A Walk',
				artist: 'Tycho',
				album: 'Dive',
				url: 'https://youtu.be/SDNA934EEVk',
				imgUrl: ['https://i.ytimg.com/vi/O8mco7B1gIg/mqdefault.jpg'],
				addedAt: 162521795263,
				duration: '6:30',
			},
			{
				id: 'chill1003',
				title: 'Midnight in a Perfect World',
				artist: 'DJ Shadow',
				album: 'Endtroducing.....',
				url: 'https://youtu.be/4JkIs37a2JE',
				imgUrl: ['https://i.ytimg.com/vi/4JkIs37a2JE/mqdefault.jpg'],
				addedAt: 162521795264,
				duration: '5:00',
			},
			{
				id: 'chill1004',
				title: 'First Fires',
				artist: 'Bonobo',
				album: 'The North Borders',
				url: 'https://youtu.be/pqhkcjZXe7M',
				imgUrl: ['https://i.ytimg.com/vi/pqhkcjZXe7M/mqdefault.jpg'],
				addedAt: 162521795265,
				duration: '4:37',
			},
			{
				id: 'chill1005',
				title: 'Eyesdown',
				artist: 'Bonobo',
				album: 'Black Sands',
				url: 'https://youtu.be/WkSy6OiUvhk',
				imgUrl: ['https://i.ytimg.com/vi/WkSy6OiUvhk/mqdefault.jpg'],
				addedAt: 162521795266,
				duration: '5:28',
			},
			{
				id: 'chill1006',
				title: 'Pink Matter',
				artist: 'Frank Ocean',
				album: 'Channel Orange',
				url: 'https://youtu.be/9qv6Q9XOnN0',
				imgUrl: ['https://i.ytimg.com/vi/9qv6Q9XOnN0/mqdefault.jpg'],
				addedAt: 162521795267,
				duration: '4:31',
			},
			{
				id: 'chill1007',
				title: 'Sunset Lover',
				artist: 'Petit Biscuit',
				album: 'Presence',
				url: 'https://youtu.be/9iHM6X6uUH8',
				imgUrl: ['https://i.ytimg.com/vi/9iHM6X6uUH8/mqdefault.jpg'],
				addedAt: 162521795268,
				duration: '3:58',
			},
			{
				id: 'chill1008',
				title: 'Loud Places',
				artist: 'Jamie xx',
				album: 'In Colour',
				url: 'https://youtu.be/G_eSLtL5P2M',
				imgUrl: ['https://i.ytimg.com/vi/G_eSLtL5P2M/mqdefault.jpg'],
				addedAt: 162521795269,
				duration: '4:43',
			},
		],
	},
	{
		_id: '5cksxjas89xjsa8xjsa8jxs02',
		name: 'Workout Energy',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724083027/rfft1keoyporqtgpv8w8.webp',
		tags: ['Workout', 'Energetic'],
		createdBy: {
			id: 'u103',
			fullname: 'Jane Doe',
			imgUrl: 'https://i.imgur.com/5ZMXSYg.jpeg',
		},
		likedByUsers: ['{user-id3}', '{user-id4}'],
		songs: [
			{
				id: 'energy1001',
				title: 'Eye of the Tiger',
				artist: 'Survivor',
				album: 'Eye of the Tiger',
				url: 'https://www.youtube.com/watch?v=btPJPFnesV4',
				imgUrl: ['https://i.ytimg.com/vi/btPJPFnesV4/mqdefault.jpg'],
				addedAt: 162521795270,
				duration: '4:04',
			},
			{
				id: 'energy1002',
				title: 'Lose Yourself',
				artist: 'Eminem',
				album: '8 Mile Soundtrack',
				url: 'https://www.youtube.com/watch?v=_Yhyp-_hX2s',
				imgUrl: ['https://i.ytimg.com/vi/_Yhyp-_hX2s/mqdefault.jpg'],
				addedAt: 162521795271,
				duration: '5:26',
			},
			{
				id: 'energy1003',
				title: 'Remember the Name',
				artist: 'Fort Minor',
				album: 'The Rising Tied',
				url: 'https://youtu.be/VDvr08sCPOc',
				imgUrl: ['https://i.ytimg.com/vi/VDvr08sCPOc/mqdefault.jpg'],
				addedAt: 162521795272,
				duration: '3:48',
			},
			{
				id: 'energy1004',
				title: 'Stronger',
				artist: 'Kanye West',
				album: 'Graduation',
				url: 'https://youtu.be/PsO6ZnUZI0g',
				imgUrl: ['https://i.ytimg.com/vi/PsO6ZnUZI0g/mqdefault.jpg'],
				addedAt: 162521795273,
				duration: '5:12',
			},
			{
				id: 'energy1005',
				title: 'Can\'t Hold Us',
				artist: 'Macklemore & Ryan Lewis',
				album: 'The Heist',
				url: 'https://youtu.be/2zNSgSzhBfM',
				imgUrl: ['https://i.ytimg.com/vi/2zNSgSzhBfM/mqdefault.jpg'],
				addedAt: 162521795274,
				duration: '4:18',
			},
			{
				id: 'energy1006',
				title: 'Power',
				artist: 'Kanye West',
				album: 'My Beautiful Dark Twisted Fantasy',
				url: 'https://youtu.be/L53gjP-TtGE',
				imgUrl: ['https://i.ytimg.com/vi/L53gjP-TtGE/mqdefault.jpg'],
				addedAt: 162521795275,
				duration: '4:52',
			},
			{
				id: 'energy1007',
				title: 'Stronger',
				artist: 'Kanye West',
				album: 'Graduation',
				url: 'https://youtu.be/3DZnUw-Qe4Y',
				imgUrl: ['https://i.ytimg.com/vi/3DZnUw-Qe4Y/mqdefault.jpg'],
				addedAt: 162521795276,
				duration: '5:00',
			},
			{
				id: 'energy1008',
				title: 'Till I Collapse',
				artist: 'Eminem',
				album: 'The Eminem Show',
				url: 'https://youtu.be/ywaJAZd4M3U',
				imgUrl: ['https://i.ytimg.com/vi/ywaJAZd4M3U/mqdefault.jpg'],
				addedAt: 162521795277,
				duration: '4:58',
			},
		],
	},
	{
		_id: '5cksxjas89xjsa8xjsa8jxs03',
		name: 'Party Hits',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724083048/mtoempa1met6lv2tc6bh.webp',
		tags: ['Party', 'Upbeat'],
		createdBy: {
			id: 'u104',
			fullname: 'John Doe',
			imgUrl: 'https://i.imgur.com/TRVS3gj.jpeg',
		},
		likedByUsers: ['{user-id5}', '{user-id6}'],
		songs: [
			{
				id: 'party1001',
				title: 'One More Time',
				artist: 'Daft Punk',
				album: 'Discovery',
				url: 'https://www.youtube.com/watch?v=FGBhQbmPwH8',
				imgUrl: ['https://i.ytimg.com/vi/FGBhQbmPwH8/mqdefault.jpg'],
				addedAt: 162521795278,
				duration: '5:20',
			},
			{
				id: 'party1002',
				title: 'Party Rock Anthem',
				artist: 'LMFAO',
				album: 'Sorry for Party Rocking',
				url: 'https://www.youtube.com/watch?v=KQ6zr6kCPj8',
				imgUrl: ['https://i.ytimg.com/vi/KQ6zr6kCPj8/mqdefault.jpg'],
				addedAt: 162521795279,
				duration: '6:16',
			},
			{
				id: 'party1003',
				title: 'Uptown Funk',
				artist: 'Mark Ronson ft. Bruno Mars',
				album: 'Uptown Special',
				url: 'https://youtu.be/OPf0YbXqDm0',
				imgUrl: ['https://i.ytimg.com/vi/OPf0YbXqDm0/mqdefault.jpg'],
				addedAt: 162521795280,
				duration: '4:31',
			},
			{
				id: 'party1004',
				title: 'Can\'t Stop the Feeling!',
				artist: 'Justin Timberlake',
				album: 'Trolls Soundtrack',
				url: 'https://youtu.be/ru0K8uYEZWw',
				imgUrl: ['https://i.ytimg.com/vi/ru0K8uYEZWw/mqdefault.jpg'],
				addedAt: 162521795281,
				duration: '3:56',
			},
			{
				id: 'party1005',
				title: 'Happy',
				artist: 'Pharrell Williams',
				album: 'G I R L',
				url: 'https://youtu.be/y6Sxv-sUYtM',
				imgUrl: ['https://i.ytimg.com/vi/y6Sxv-sUYtM/mqdefault.jpg'],
				addedAt: 162521795282,
				duration: '4:07',
			},
			{
				id: 'party1006',
				title: 'I Gotta Feeling',
				artist: 'The Black Eyed Peas',
				album: 'The E.N.D.',
				url: 'https://youtu.be/uSD4vsh1zDA',
				imgUrl: ['https://i.ytimg.com/vi/uSD4vsh1zDA/mqdefault.jpg'],
				addedAt: 162521795283,
				duration: '4:49',
			},
			{
				id: 'party1007',
				title: 'Blinding Lights',
				artist: 'The Weeknd',
				album: 'After Hours',
				url: 'https://youtu.be/4NRXx6U8ABQ',
				imgUrl: ['https://i.ytimg.com/vi/4NRXx6U8ABQ/mqdefault.jpg'],
				addedAt: 162521795284,
				duration: '3:22',
			},
			{
				id: 'party1008',
				title: 'Levitating',
				artist: 'Dua Lipa ft. DaBaby',
				album: 'Future Nostalgia',
				url: 'https://youtu.be/TUVcZfQe-Kw',
				imgUrl: ['https://i.ytimg.com/vi/TUVcZfQe-Kw/mqdefault.jpg'],
				addedAt: 162521795285,
				duration: '3:23',
			},
		],
	},
	{
		_id: '5cksxjas89xjsa8xjsa8jxs04',
		name: 'Acoustic Bliss',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724083050/acoustic.jpg',
		tags: ['Acoustic', 'Soothing'],
		createdBy: {
			id: 'u105',
			fullname: 'Emily Clark',
			imgUrl: 'https://i.imgur.com/JQkW0e4.jpeg',
		},
		likedByUsers: ['{user-id7}', '{user-id8}'],
		songs: [
			{
				id: 'acoustic1001',
				title: 'Skinny Love',
				artist: 'Bon Iver',
				album: 'For Emma, Forever Ago',
				url: 'https://youtu.be/ssdgFoHLwnk',
				imgUrl: ['https://i.ytimg.com/vi/ssdgFoHLwnk/mqdefault.jpg'],
				addedAt: 162521795286,
				duration: '3:59',
			},
			{
				id: 'acoustic1002',
				title: 'Let Her Go',
				artist: 'Passenger',
				album: 'All the Little Lights',
				url: 'https://youtu.be/RBumgq5yVrA',
				imgUrl: ['https://i.ytimg.com/vi/RBumgq5yVrA/mqdefault.jpg'],
				addedAt: 162521795287,
				duration: '4:15',
			},
			{
				id: 'acoustic1003',
				title: 'The A Team',
				artist: 'Ed Sheeran',
				album: '+',
				url: 'https://youtu.be/UAWcs5H-qgQ',
				imgUrl: ['https://i.ytimg.com/vi/UAWcs5H-qgQ/mqdefault.jpg'],
				addedAt: 162521795288,
				duration: '4:18',
			},
			{
				id: 'acoustic1004',
				title: 'Bloom',
				artist: 'The Paper Kites',
				album: 'Woodland',
				url: 'https://youtu.be/8inJtTG_DuU',
				imgUrl: ['https://i.ytimg.com/vi/8inJtTG_DuU/mqdefault.jpg'],
				addedAt: 162521795289,
				duration: '3:33',
			},
			{
				id: 'acoustic1005',
				title: 'Ho Hey',
				artist: 'The Lumineers',
				album: 'The Lumineers',
				url: 'https://youtu.be/zvCBSSwgtg4',
				imgUrl: ['https://i.ytimg.com/vi/zvCBSSwgtg4/mqdefault.jpg'],
				addedAt: 162521795290,
				duration: '2:42',
			},
			{
				id: 'acoustic1006',
				title: 'Rivers and Roads',
				artist: 'The Head and the Heart',
				album: 'The Head and the Heart',
				url: 'https://youtu.be/eLPsQLzMFbI',
				imgUrl: ['https://i.ytimg.com/vi/eLPsQLzMFbI/mqdefault.jpg'],
				addedAt: 162521795291,
				duration: '4:43',
			},
			{
				id: 'acoustic1007',
				title: 'Take Me Home, Country Roads',
				artist: 'John Denver',
				album: 'Poems, Prayers & Promises',
				url: 'https://youtu.be/1vrEljMfXYo',
				imgUrl: ['https://i.ytimg.com/vi/1vrEljMfXYo/mqdefault.jpg'],
				addedAt: 162521795292,
				duration: '3:17',
			},
			{
				id: 'acoustic1008',
				title: 'Fast Car',
				artist: 'Tracy Chapman',
				album: 'Tracy Chapman',
				url: 'https://youtu.be/uTIB10eQnA0',
				imgUrl: ['https://i.ytimg.com/vi/uTIB10eQnA0/mqdefault.jpg'],
				addedAt: 162521795293,
				duration: '4:57',
			},
		],
	},
	{
		_id: '5cksxjas89xjsa8xjsa8jxs05',
		name: 'Classical Essentials',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724083051/classical.jpg',
		tags: ['Classical', 'Instrumental'],
		createdBy: {
			id: 'u106',
			fullname: 'Michael Johnson',
			imgUrl: 'https://i.imgur.com/lhthbwE.jpeg',
		},
		likedByUsers: ['{user-id9}', '{user-id10}'],
		songs: [
			{
				id: 'classical1001',
				title: 'Canon in D',
				artist: 'Johann Pachelbel',
				album: 'Classical Essentials',
				url: 'https://youtu.be/JvNQLJ1_HQ0',
				imgUrl: ['https://i.ytimg.com/vi/JvNQLJ1_HQ0/mqdefault.jpg'],
				addedAt: 162521795294,
				duration: '4:00',
			},
			{
				id: 'classical1002',
				title: 'Für Elise',
				artist: 'Ludwig van Beethoven',
				album: 'Classical Essentials',
				url: 'https://youtu.be/_mVW8tgGY_w',
				imgUrl: ['https://i.ytimg.com/vi/_mVW8tgGY_w/mqdefault.jpg'],
				addedAt: 162521795295,
				duration: '2:52',
			},
			{
				id: 'classical1003',
				title: 'The Four Seasons: Spring',
				artist: 'Antonio Vivaldi',
				album: 'Classical Essentials',
				url: 'https://youtu.be/Ei1prVczE5k',
				imgUrl: ['https://i.ytimg.com/vi/Ei1prVczE5k/mqdefault.jpg'],
				addedAt: 162521795296,
				duration: '3:34',
			},
			{
				id: 'classical1004',
				title: 'Symphony No. 5',
				artist: 'Ludwig van Beethoven',
				album: 'Classical Essentials',
				url: 'https://youtu.be/fOk8Tm815lE',
				imgUrl: ['https://i.ytimg.com/vi/fOk8Tm815lE/mqdefault.jpg'],
				addedAt: 162521795297,
				duration: '7:29',
			},
			{
				id: 'classical1005',
				title: 'Clair de Lune',
				artist: 'Claude Debussy',
				album: 'Classical Essentials',
				url: 'https://youtu.be/CvFH_6DNRCY',
				imgUrl: ['https://i.ytimg.com/vi/CvFH_6DNRCY/mqdefault.jpg'],
				addedAt: 162521795298,
				duration: '5:02',
			},
			{
				id: 'classical1006',
				title: 'Moonlight Sonata',
				artist: 'Ludwig van Beethoven',
				album: 'Classical Essentials',
				url: 'https://youtu.be/4Tr0otuiQuU',
				imgUrl: ['https://i.ytimg.com/vi/4Tr0otuiQuU/mqdefault.jpg'],
				addedAt: 162521795299,
				duration: '5:32',
			},
			{
				id: 'classical1007',
				title: 'Gymnopédie No.1',
				artist: 'Erik Satie',
				album: 'Classical Essentials',
				url: 'https://youtu.be/S-Xm7s9eGxU',
				imgUrl: ['https://i.ytimg.com/vi/S-Xm7s9eGxU/mqdefault.jpg'],
				addedAt: 162521795300,
				duration: '3:23',
			},
			{
				id: 'classical1008',
				title: 'The Swan',
				artist: 'Camille Saint-Saëns',
				album: 'Classical Essentials',
				url: 'https://youtu.be/28XO5T_RStQ',
				imgUrl: ['https://i.ytimg.com/vi/28XO5T_RStQ/mqdefault.jpg'],
				addedAt: 162521795301,
				duration: '3:09',
			},
		],
	},
	{
		_id: '5cksxjas89xjsa8xjsa8jxs06',
		name: 'Indie Mix',
		imgUrl: 'https://res.cloudinary.com/dh73ujhyv/image/upload/v1724083052/indie.jpg',
		tags: ['Indie', 'Alternative'],
		createdBy: {
			id: 'u107',
			fullname: 'Sarah Lee',
			imgUrl: 'https://i.imgur.com/Oeh2k1J.jpeg',
		},
		likedByUsers: ['{user-id11}', '{user-id12}'],
		songs: [
			{
				id: 'indie1001',
				title: 'Take Me Out',
				artist: 'Franz Ferdinand',
				album: 'Franz Ferdinand',
				url: 'https://youtu.be/IYvf9R7ts5M',
				imgUrl: ['https://i.ytimg.com/vi/IYvf9R7ts5M/mqdefault.jpg'],
				addedAt: 162521795302,
				duration: '3:58',
			},
			{
				id: 'indie1002',
				title: 'Fluorescent Adolescent',
				artist: 'Arctic Monkeys',
				album: 'Favourite Worst Nightmare',
				url: 'https://youtu.be/ma9I9VBKPiw',
				imgUrl: ['https://i.ytimg.com/vi/ma9I9VBKPiw/mqdefault.jpg'],
				addedAt: 162521795303,
				duration: '3:12',
			},
			{
				id: 'indie1003',
				title: 'Somebody Told Me',
				artist: 'The Killers',
				album: 'Hot Fuss',
				url: 'https://youtu.be/Y5fBdpreJiU',
				imgUrl: ['https://i.ytimg.com/vi/Y5fBdpreJiU/mqdefault.jpg'],
				addedAt: 162521795304,
				duration: '3:17',
			},
			{
				id: 'indie1004',
				title: 'Dog Days Are Over',
				artist: 'Florence + The Machine',
				album: 'Lungs',
				url: 'https://youtu.be/iWOyfLBYtuU',
				imgUrl: ['https://i.ytimg.com/vi/iWOyfLBYtuU/mqdefault.jpg'],
				addedAt: 162521795305,
				duration: '4:12',
			},
			{
				id: 'indie1005',
				title: 'Young Folks',
				artist: 'Peter Bjorn and John',
				album: 'Writer\'s Block',
				url: 'https://youtu.be/51V1VMkuyx0',
				imgUrl: ['https://i.ytimg.com/vi/51V1VMkuyx0/mqdefault.jpg'],
				addedAt: 162521795306,
				duration: '4:38',
			},
			{
				id: 'indie1006',
				title: 'Electric Feel',
				artist: 'MGMT',
				album: 'Oracular Spectacular',
				url: 'https://youtu.be/-nwdjQmc_N8',
				imgUrl: ['https://i.ytimg.com/vi/-nwdjQmc_N8/mqdefault.jpg'],
				addedAt: 162521795307,
				duration: '3:50',
			},
			{
				id: 'indie1007',
				title: 'Do I Wanna Know?',
				artist: 'Arctic Monkeys',
				album: 'AM',
				url: 'https://youtu.be/bpOSxM0rNPM',
				imgUrl: ['https://i.ytimg.com/vi/bpOSxM0rNPM/mqdefault.jpg'],
				addedAt: 162521795308,
				duration: '4:23',
			},
			{
				id: 'indie1008',
				title: 'Lisztomania',
				artist: 'Phoenix',
				album: 'Wolfgang Amadeus Phoenix',
				url: 'https://youtu.be/4BJDNw7o6so',
				imgUrl: ['https://i.ytimg.com/vi/4BJDNw7o6so/mqdefault.jpg'],
				addedAt: 162521795309,
				duration: '4:02',
			},
		],
	},
];



const user = {
	_id: 'u102',
	username: 'musicLover123',
	img: 'https://example.com/user-img.jpg',
	likedSongs: [
		{
			id: 's1001',
			title: 'Cissy Strut',
			artist: 'The Meters',
			album: 'Funky Monks',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/4_iC0MyIykM/mqdefault.jpg'],
			addedAt: 162521765262,
			duration: '3:00',
		},
		{
			id: 'mUkfiLjo1xs',
			title: "Pass The Peas",
			artist: "The JB's",
			album: 'Funky Monks',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/mUkfiLjooxs/mqdefault.jpg'],
			addedAt: 162521765262,
			duration: '4:00',
		},
		{
			id: 'mUkfiLj2oxs',
			title: "Pass The Peas",
			artist: "The JB's",
			album: 'Funky Monks',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/mUkfiLjooxs/mqdefault.jpg'],
			addedAt: 162521765262,
			duration: '2:30',
		},
		{
			id: 'mUkfiLj5oxs',
			title: "Pass The Peas",
			artist: "The JB's",
			album: 'Funky Monks',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/mUkfiLjooxs/mqdefault.jpg'],
			addedAt: 162521765262,
			duration: '2:30',
		},
		{
			id: 'qJ5F2P5tYmE',
			title: 'Superstition',
			artist: 'Stevie Wonder',
			album: 'Talking Book',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/qJ5F2P5tYmE/mqdefault.jpg'],
			addedAt: 162521775262,
			duration: '4:26',
		},

		{
			id: 'l8A7O4u4L9w',
			title: 'Give Up the Funk',
			artist: 'Parliament',
			album: 'Mothership Connection',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/l8A7O4u4L9w/mqdefault.jpg'],
			addedAt: 162521785262,
			duration: '5:45',
		},
		{
			id: 'WwSRA2p4He0',
			title: 'Dance to the Music',
			artist: 'Sly & The Family Stone',
			album: 'Dance to the Music',
			url: 'youtube/song.mp4',
			imgUrl: ['https://i.ytimg.com/vi/WwSRA2p4He0/mqdefault.jpg'],
			addedAt: 162521795262,
			duration: '3:00',
		},
	],
	likedStations: [
		{
			id: '5cksxjas89xjsa8xjsa8jxs09',
			name: 'Moody',
			creator: 'Puki Ben David',
			album: 'Moody',
			img: ['default-img'],
		},
		{
			id: 's102',
			name: 'Funky Monks',
			creator: 'Puki Ben David',
			album: 'Funky Monks',
			img: ['default-img'],
		},
	],
}

export { stations, user };

// function isLikedByUser(songId){}
